# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.synced_folder "..", "/inotify", 
    mount_options: ["dmode=775,fmode=775"]

  config.vm.hostname = "test-linux.vagrant"
  config.vm.provision :shell, path: "bootstrap.sh"
end
